<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Welcome to Artoword</title>    

       <?php include ("Style.phtml"); ?>
      
    </head>
    <body>


<?php include ("Header.phtml"); ?>


       <div  class= "image">
            <?php  foreach($Articles as $a ){ ?>



<?php 
$link=realpath("/img/");

$source = imagecreatefromjpeg($link."$a->ImageArticle"); // La photo est la source
$destination = imagecreatetruecolor(300,300); // On crée la miniature vide

// Les fonctions imagesx et imagesy renvoient la largeur et la hauteur d'une image
$largeur_source = imagesx($source);
$hauteur_source = imagesy($source);
$largeur_destination = imagesx($destination);
$hauteur_destination = imagesy($destination);

// On crée la miniature
imagecopyresampled($destination, $source, 0, 0, 0, 0, $largeur_destination, $hauteur_destination, $largeur_source, $hauteur_source);

// On enregistre la miniature sous le nom "mini_couchersoleil.jpg"
imagejpeg($destination, $link.$a->ImageArticle);


?>

<div >


            <div>  <a  href="/article/<?=  $a->id  ?>"  ><img src="/img/<?= $a->ImageArticle ?>"> </a>

                 <div class="description">  
                <h4><p> Title <a href="/article/<?=  $a->id  ?>"> <?=  $a->Title  ?> </a><br><br>
                        
                        Summary  : <?= $a->Summary ?> </p></h4>   
                       Comment:  <?= $a->Comment ?>  <br>
               
                        <a href="/upd/<?=  $a->id  ?>"> Update </a> 
                        <a href="/sub/<?=  $a->id  ?>"> Delete </a> 
                        <br><br>

                </div>
             </div>


<br><br>
</div>
            <?php } ?>

</div>


<?php include ("Footer.phtml"); ?>
      
      
    </body>
</html>
