<!DOCTYPE html>
<html>
<head>
	<title>Articulus7-Conctact-Us</title>
	<?php include ("Style.phtml"); ?>
</head>
<body>

<?php include ("Header.phtml"); ?>

<h2> Contact Us </h2>


<div> 
<p>Articulus7 would like to hear from you. If you are not sure who to contact, please send email to hmkisebwe@gmail.com</a> </p>

<br><br>
</div>
<div>
<p>General information</p>
<p> <a href="https://fr.linkedin.com/in/hugo-kisebwe-82b399b9"> kisebwe Hugo</a> CEO  of Articulus7
</div>

<div>
<p>Support</p>
</div>





<?php include ("Footer.phtml"); ?>
</body>
</html>

