<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Articulus7-create an article</title>
        <?php include ("Style.phtml") ?>
     
    </head>
    <body>
       

<?php include ("Header.phtml") ?>

 <h1> Add your great article ! </h3> <br>


        <div> <p>

<form action="/add" method="post" enctype="multipart/form-data">
 
  <p> Tilte :<input type="text" name="title"> </p>
  <p> Comment :<input type="text" name="comment"></p>
 <p> Summary :  <textarea type="text" name="summary"  rows="5" cols="50">  </textarea></p>

  
   <input type="file" name="ImageArticle" /><br />
    <input type="submit" name="Valider">



      
</form>


     

</p>

</div>


<?php include ("Footer.phtml") ?>
      
      
    </body>
</html>
