<br> <br> <br> 

<footer>

	<div>
<br><br>
	    <a href="/add">Add new great article </a>  <br> <br><br> <br><br> <br> <br><br> <br>
		<a href="/">Articulus7 &nbsp;</a>
	
		<a href="/ContactUs">Contact Us &nbsp; </a>
	
		<a href="/Right">Copyright&nbsp;</a> <br>

		<a href="/install">reinstall app  </a>
	</div>
	<div id=".im">

	<br> 
		<p>Copyright © 2017 by <a href="https://fr.linkedin.com/in/hugo-kisebwe-82b399b9"> kisebwe Hugo</a>, Paris - Article Search Engine Directory at Artoword™
All Rights Reserved Worldwide. All Trademarks and Servicemarks are the property of the respective owners.</p>
	</div>



</footer>


