<div id="bloc_page">
  <header>

    <div id="titre_principale">
      <h1> Articilus </h1>
    </div>

    <h4> Number 1 of personal articles management in the World </h5>

</div>


<nav>
<div>
<h3>

<div>
<ul >

<li><a href="/"> Home </a></li>
<li><a href="#"> Category</a> </li>
<li><a href="/add"> Add an article </a> </li>
<li><a href="/ContactUs"> Conctact us </a></li>
</ul>

</div>

</h3>
</div>
</nav>
<br> <br> <br> <br> 
</header>
