

<!DOCTYPE html>
<html>
<head>
	<title>Artoword-Right</title>
	<?php include ("Style.phtml"); ?>
</head>
<body>

<?php include ("Header.phtml"); ?>


<h2> Articuclus7.com Copyright </h2>

<p>
	Materials in this website are copyrighted and all rights are reserved.

Articulus7.com either owns the intellectual property rights in the underlying HTML, text, images,scripts, software and other content (collectively, the "Content") that is made available to you on this website, or has obtained the permission of the owner of the intellectual property in such Content to use the Content on this website.

The Content is protected by US and International Copyright Laws.
</p>


<?php include ("Footer.phtml"); ?>
</body>
</html>