  

 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">


<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
  <style>
            body {
                margin: 50px 0 0 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #aaa;
                font-size: 19px;
            }

            h1 {
                color: #719e40;
                letter-spacing: -3px;
                font-family: 'Lato', sans-serif;
                font-size: 75px;
                font-weight: 200;
                margin-bottom: 0;
            }



            h2{

                color: #719e40;


            }




            /* Navigation */

nav ul
{
    list-style-type: none;


    

}

nav li
{
    margin-right: 35px;
    display: inline;
}

nav a
{
    font-size: 1.3em;
    
    padding-bottom: 3px;
    text-decoration: none;
}




.image{

    display: flex;
    flex-flow: row wrap;
    margin: auto
     margin-right: 200px;
     justify-content: space-around;
    }

.description {
    width: 300px;
}

 </style>

